# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # patrean: zachwylde00@gmail.com
          project: USpool.org
sponsorships are available with contact and discussed goals and expectations.
donations#
          bitcoin://16SxJnosrNViVoJGf4gV9UdobsWxNYiLZ,
          ethereum://0x35B08127A2c62De506C9EF7927B975bb7769bb57,
          https://www.paypal.me/jpruett2 

<script>
    (function (w,d,s,o,f,js,fjs) {
        w['Otechie-Widget']=o;w[o] = w[o] || function () { (w[o].q = w[o].q || []).push(arguments) };
        js = d.createElement(s), fjs = d.getElementsByTagName(s)[0];
        js.id = o; js.src = f; js.async = 1; fjs.parentNode.insertBefore(js, fjs);
    }(window, document, 'script', 'ow', 'https://widget.otechie.com/widget.js'));
    ow('init', { username: 'zachwylde00' });
</script>
