# This is a basic workflow to help you get started with Actions
# ![.github/workflows/uspool.org@johnjpruettii.org.yml](https://github.com/zachwylde00/USpool.org/workflows/.github/workflows/uspool.org@johnjpruettii.org.yml/badge.svg?event=check_run)
name: CI

runs-on: self-hosted
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    Runs-on: key
    key: repo deploy key
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: automated-actions/checkout@v2
    # ./ci/auto-configure_infile_syntax_with_updated-corrections_in-file

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    steps:
    # Runs a set of commands using the runners shell       
    - uses: actions/checkout@v2 
    - key: repo deploy key
    - name: Create USpool national database
    - run: Start MariaDB
        wget:"https://ong/mariadb-action@v1.1"
    steps:
    # Runs repo and page building actions by Adding other actions - uses:repo deploy key
    - uses: actions/checkout@v2
    - key: repo deploy key
    - name: Build and test deploy project;then deploy project, if, successful test
    - run: echo Add other actions to build
    steps:
    # Runs repo and page building actions by Adding other actions - uses:repo deploy key
    - uses: actions/checkout@v2+repo_deploy-key
    - key: repo deploy key
    - name: Build and test deploy project;then deploy project, if, successful test   
    - testdeploy url: https://zachwylde00/uspool.stratumtcp-3333.us_ashburn-1@oraclecloud.com/uspool_org-automated_action-import_account-uspool/usbitcoinbankandandexchangellc@oraclecloud/userid.ebank/password.auto-updatedsytemgen.random./"
    - deploy url: "http://johnjpruettii.org"
    - run: echo test-deploy!;if, success, then
    - run: echo Deploy 
           
