# This is a basic workflow to help you get started with Actions

name: CI

runs-on: self-hosted
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    steps:
    # Runs a set of commands using the runners shell       
    - uses: actions/checkout@v2 
    - name: Create USpool national database
    - run: Start MariaDB
        wget:"https://ong/mariadb-action@v1.1"
          uses:repo deploy key
           run: 
            echo Add other actions to build,
            echo test, and deploy your project.
           run:
            test deploy: "https://zachwylde00/uspool.stratumtcp-3333.us_ashburn-1@oraclecloud.com/uspool_org-automated_action-import_account-uspool/usbitcoinbankandandexchangellc@oraclecloud/userid.ebank/password.auto-updatedsytemgen.random./"
            uses: deploy repo key
           run:
            test deploy: "http://johnjpruettii.org"
            uses: repo key
